version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: 192.168.10.4
      MYSQL_USER: root
      MYSQL_PASSWORD: angaispassword
      MYSQL_DATABASE: serenades

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
